### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by klapuch** [dasuos/Routing#1]
- [x] `namespace Krnak\Core` => `namespace Krnak\Routing`
- [x] Uri interface - there will be at least 2 implementation - Fake and the real one
- [x] Test for `/controller/ /parameter/action`
- [x] Make .gitignore file and ignore `vendor/` `composer.lock` `.idea` (.idea should be in global .gitignore)
- [x] Don't use fully qualified namespaces - rewrite it to `Routing\NormalisedUrl`
- [x] Add `@testCase` and `@phpVersion` to tests - https://tester.nette.org/cs/#toc-testcase-2

**Comment by dasuos** [comment]
thx for tips bro :D

**Comment by klapuch** [comment]
@dasuos Cool, you did it.
